export const DEFAULT_SITE_ASSETS = [
  // Section "Hero & Banners"
  { slot_key: 'ui-hero-video', label: 'Main Hero Scroll Video (MP4/WebM)', section: 'Hero & Banners', media_type: 'video', cloudinary_public_id: 'ui-hero-video' },
  { slot_key: 'ui-hero-main', label: 'Main Hero Banner', section: 'Hero & Banners' },
  { slot_key: 'ui-workshop', label: 'Workshop / Craftsmanship Image', section: 'Hero & Banners' },
  { slot_key: 'ui-showroom-banner', label: 'Showroom Banner', section: 'Hero & Banners' },

  // Section "Estimator - Property & Rooms"
  { slot_key: 'est-prop-1bhk', label: '1 BHK Property', section: 'Estimator - Property & Rooms' },
  { slot_key: 'est-prop-2bhk', label: '2 BHK Property', section: 'Estimator - Property & Rooms' },
  { slot_key: 'est-prop-3bhk', label: '3 BHK Property', section: 'Estimator - Property & Rooms' },
  { slot_key: 'est-prop-4bhk', label: '4 BHK Property', section: 'Estimator - Property & Rooms' },
  { slot_key: 'est-prop-villa', label: 'Villa / Duplex', section: 'Estimator - Property & Rooms' },
  { slot_key: 'est-room-living', label: 'Living Room', section: 'Estimator - Property & Rooms' },
  { slot_key: 'est-room-dining', label: 'Dining Room', section: 'Estimator - Property & Rooms' },
  { slot_key: 'est-room-kitchen', label: 'Kitchen', section: 'Estimator - Property & Rooms' },
  { slot_key: 'est-room-master-bedroom', label: 'Master Bedroom', section: 'Estimator - Property & Rooms' },
  { slot_key: 'est-room-bedroom-2', label: 'Bedroom 2', section: 'Estimator - Property & Rooms' },
  { slot_key: 'est-room-bedroom-3', label: 'Bedroom 3', section: 'Estimator - Property & Rooms' },
  { slot_key: 'est-room-study-office', label: 'Study / Office', section: 'Estimator - Property & Rooms' },

  // Section "Estimator - Packages"
  { slot_key: 'est-pkg-essential', label: 'Essential Package', section: 'Estimator - Packages' },
  { slot_key: 'est-pkg-premium', label: 'Premium Package', section: 'Estimator - Packages' },
  { slot_key: 'est-pkg-luxury', label: 'Luxury Package', section: 'Estimator - Packages' },
  { slot_key: 'est-pkg-smart-luxury', label: 'Smart Luxury Package', section: 'Estimator - Packages' },

  // Section "Estimator - Kitchen"
  { slot_key: 'est-kit-modular', label: 'Modular Kitchen (Main)', section: 'Estimator - Kitchen' },
  { slot_key: 'est-kit-complete', label: 'Complete Kitchen', section: 'Estimator - Kitchen' },
  { slot_key: 'est-kit-l-shaped', label: 'L-Shaped Kitchen', section: 'Estimator - Kitchen' },
  { slot_key: 'est-kit-u-shaped', label: 'U-Shaped Kitchen', section: 'Estimator - Kitchen' },
  { slot_key: 'est-kit-galley', label: 'Galley Kitchen', section: 'Estimator - Kitchen' },
  { slot_key: 'est-kit-island', label: 'Island Kitchen', section: 'Estimator - Kitchen' },
  { slot_key: 'est-kit-peninsula', label: 'Peninsula Kitchen', section: 'Estimator - Kitchen' },
  { slot_key: 'est-kit-single-wall', label: 'Single Wall Kitchen', section: 'Estimator - Kitchen' },
  { slot_key: 'est-kit-base-cabinet', label: 'Base Cabinet', section: 'Estimator - Kitchen' },
  { slot_key: 'est-kit-upper-cabinet', label: 'Upper Cabinet', section: 'Estimator - Kitchen' },
  { slot_key: 'est-kit-tall-cabinet', label: 'Tall Cabinet', section: 'Estimator - Kitchen' },

  // Section "Estimator - Wardrobe"
  { slot_key: 'est-wd-complete', label: 'Complete Wardrobe', section: 'Estimator - Wardrobe' },
  { slot_key: 'est-wd-hinged', label: 'Hinged Wardrobe', section: 'Estimator - Wardrobe' },
  { slot_key: 'est-wd-sliding', label: 'Sliding Wardrobe 1', section: 'Estimator - Wardrobe' },
  { slot_key: 'est-wd-sliding2', label: 'Sliding Wardrobe 2', section: 'Estimator - Wardrobe' },
  { slot_key: 'est-wd-walk-in', label: 'Walk-in Wardrobe', section: 'Estimator - Wardrobe' },
  { slot_key: 'est-wd-built-in-niche', label: 'Built-in Niche Wardrobe', section: 'Estimator - Wardrobe' },
  { slot_key: 'est-wd-balanced-combo', label: 'Balanced Combo Wardrobe', section: 'Estimator - Wardrobe' },
  { slot_key: 'est-wd-drawer-heavy', label: 'Drawer Heavy Wardrobe', section: 'Estimator - Wardrobe' },
  { slot_key: 'est-wd-shelving-focus', label: 'Shelving Focus Wardrobe', section: 'Estimator - Wardrobe' },
  { slot_key: 'est-wd-hanging-focus', label: 'Hanging Focus Wardrobe', section: 'Estimator - Wardrobe' },
  { slot_key: 'est-wd-jewellery-drawer', label: 'Jewellery Drawer', section: 'Estimator - Wardrobe' },
  { slot_key: 'est-wd-pulldown-hanger', label: 'Pulldown Hanger', section: 'Estimator - Wardrobe' },
  { slot_key: 'est-wd-trouser-rack', label: 'Trouser Rack', section: 'Estimator - Wardrobe' },
  { slot_key: 'est-wd-mirror', label: 'Mirror', section: 'Estimator - Wardrobe' },

  // Section "Estimator - Bedroom & Living"
  { slot_key: 'est-bed-complete-room', label: 'Complete Bedroom', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-bed-only', label: 'Bed Only', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-bed-with-side-table', label: 'Bed with Side Table', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-bed-with-wardrobe', label: 'Bed with Wardrobe', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-bed-king-size', label: 'King Size Bed', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-bed-queen-size', label: 'Queen Size Bed', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-bed-storage', label: 'Storage Bed', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-bed-simple-wooden', label: 'Simple Wooden Bed', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-bed-upholstered', label: 'Upholstered Bed', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-tv-base-only', label: 'TV Base Only', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-tv-base-cabinet', label: 'TV Base Cabinet', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-tv-full-wall', label: 'TV Full Wall', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-tv-open-shelves', label: 'TV Open Shelves', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-tv-wall-cabinet', label: 'TV Wall Cabinet', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-tv-drawers', label: 'TV Drawers', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-wall-fluted-panel', label: 'Fluted Wall Panel', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-wall-full-paneling', label: 'Full Wall Paneling', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-wall-paneling', label: 'Wall Paneling', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-liv-display-storage', label: 'Living Room Display Storage', section: 'Estimator - Bedroom & Living' },
  { slot_key: 'est-liv-sofas-beds', label: 'Sofas & Beds', section: 'Estimator - Bedroom & Living' },

  // Section "Estimator - Materials, Finishes & Office"
  { slot_key: 'est-mat-plywood', label: 'Plywood', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-mat-hdhmr', label: 'HDHMR', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-mat-hdhmr-laminate', label: 'HDHMR Laminate', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-mat-plywood-veneer', label: 'Plywood Veneer', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-fin-laminate', label: 'Laminate Finish', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-fin-veneer', label: 'Veneer Finish', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-fin-pu', label: 'PU Finish', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-fin-glossy-acrylic', label: 'Glossy Acrylic Finish', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-fin-matte-laminate', label: 'Matte Laminate Finish', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-hw-self-close', label: 'Self Close Hardware', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-hw-handleless-push', label: 'Handleless Push Hardware', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-off-complete', label: 'Complete Office', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-off-workstation', label: 'Workstation', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-off-manager-cabin', label: 'Manager Cabin', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-off-meeting-room', label: 'Meeting Room', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-off-cable-mgmt', label: 'Cable Management', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-add-backlighting', label: 'Backlighting', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-add-decorative-light', label: 'Decorative Light', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-add-internal-light', label: 'Internal Light', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-add-false-ceiling', label: 'False Ceiling', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-add-curtains', label: 'Curtains', section: 'Estimator - Materials, Finishes & Office' },
  { slot_key: 'est-add-wall-paint-texture', label: 'Wall Paint Texture', section: 'Estimator - Materials, Finishes & Office' },
];
